### ISSUE TITLE
Slicing issue (due to hole material?)

### ISSUE THREAD

**Issue by companje** [Doodle3D/Doodle3D-Slicer#42]
https://share.doodle3d.com/da774b99af2b4b78c420b84dc774ae21

Something strange happens with the windows. (bottom and top)

![img](https://user-images.githubusercontent.com/156066/37196351-c14e1fb6-2376-11e8-8604-69d93153b423.png)

<img width="1082" alt="screen shot 2018-03-09 at 08 50 50" src="https://user-images.githubusercontent.com/156066/37196546-89db3400-2377-11e8-9294-e5d781e4b915.png">

![screen shot 2018-03-09 at 08 52 01](https://user-images.githubusercontent.com/156066/37196424-fee3535a-2376-11e8-8de8-a59e2cdd9a8b.png)

<img width="673" alt="screen shot 2018-03-09 at 08 53 12" src="https://user-images.githubusercontent.com/156066/37196463-2cb24c50-2377-11e8-9f28-a747bc75202d.png">

[3dsketch + gcode file.zip](https://github.com/Doodle3D/Doodle3D-Slicer/files/1795999/3dsketch.gcode.file.zip)

**Comment by companje** [comment]
When I remove the objects with hole material applied the problem does not occur:

![screen shot 2018-03-09 at 09 00 19](https://user-images.githubusercontent.com/156066/37196767-5f352f2a-2378-11e8-8c39-712e7f08df25.png)

![screen shot 2018-03-09 at 09 01 06](https://user-images.githubusercontent.com/156066/37196777-61932c18-2378-11e8-9f8b-f122c9f8ce99.png)

**Comment by casperlamboo** [comment]
I've found another model which has the same problem (I think).
[Chess error.d3sketch.zip](https://github.com/Doodle3D/Doodle3D-Slicer/files/1893854/Chess.error.d3sketch.zip)

As you can see there appears to be a hole near the top of the model
<img width="940" alt="schermafbeelding 2018-04-10 om 11 01 17" src="https://user-images.githubusercontent.com/6638028/38547069-89ed0f72-3cae-11e8-82c5-6def4ebb2095.png">

When I analyse the model in Blender it appears that a lot of points are added to this part of the model
<img width="1392" alt="schermafbeelding 2018-04-10 om 11 02 39" src="https://user-images.githubusercontent.com/6638028/38547133-b5590ac6-3cae-11e8-8ce1-d0a9a7fc1874.png">

When I look at the data generated in the `slices to gcode` step for layer 263 I can see that a lot of line segments are overlapping.
<img width="787" alt="schermafbeelding 2018-04-10 om 11 02 57" src="https://user-images.githubusercontent.com/6638028/38547173-ce098d2a-3cae-11e8-95c0-6d28ea5172a6.png">

I'm guessing that due to the duplicate points some of the line segments are added multiple twice making it hard/impossible to stitch the line segments together.
